global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']
  - job_name: '192.168.1.4'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.4:9182']
